Announcments search view
folix-01/announcement.engine pull request #20
Opened 2022-06-27 15:29 UTC by foxtrot-dfm1

2022-06-30 14:55 UTC, cekk requested changes

2022-06-30 14:55 UTC, cekk commented on src/announcement/engine/browser/static/announcement_search.js
> +const SEARCH_URL = location.origin + '/' + location.pathname.split('/')[1] + '/@querystring-search';
consiglio: se non strettamente necessario, non usare querystring-search perché aggiunge troppa complessità.
Puoi fare tutto con @search.

2022-06-30 14:55 UTC, cekk commented on src/announcement/engine/browser/static/announcement_search.js
> +const SEARCH_URL = location.origin + '/' + location.pathname.split('/')[1] + '/@querystring-search';
Altra cosa: se guardi nell'html generato da Plone, potresti trovare cose interessanti per la composizione dell'url

2022-07-01 11:19 UTC, foxtrot-dfm1 commented on src/announcement/engine/browser/static/announcement_search.js
> +const SEARCH_URL = location.origin + '/' + location.pathname.split('/')[1] + '/@querystring-search';
solved

2022-07-01 11:20 UTC, foxtrot-dfm1 commented on src/announcement/engine/browser/static/announcement_search.js
> +const SEARCH_URL = location.origin + '/' + location.pathname.split('/')[1] + '/@querystring-search';
solved

2023-07-31 19:13 UTC, closed without merging